### ISSUE TITLE
Could not pass event PlayerDropItemEvent to FastTravelSigns v1.0.4

### ISSUE THREAD

**Issue by NigelThorne** [oneill011990/FastTravelReborn#8]
I'm getting the following stack trace... 

```
[20:08:05 ERROR]: Could not pass event PlayerDropItemEvent to FastTravelSigns v1.0.4
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[minecraft_server.jar:git-Spigot-7d78b81-a6d8fa2]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-7d78b81-a6d8fa2]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [minecraft_server.jar:git-Spigot-7d78b81-a6d8fa2]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [minecraft_server.jar:git-Spigot-7d78b81-a6d8fa2]
at net.minecraft.server.v1_11_R1.EntityHuman.a(EntityHuman.java:581) [minecraft_server.jar:git-Spigot-7d78b81-a6d8fa2]
at net.minecraft.server.v1_11_R1.EntityHuman.drop(EntityHuman.java:539) [minecraft_server.jar:git-Spigot-7d78b81-a6d8fa2]
at net.minecraft.server.v1_11_R1.CommandGive.execute(SourceFile:75) [minecraft_server.jar:git-Spigot-7d78b81-a6d8fa2]
at org.bukkit.craftbukkit.v1_11_R1.command.VanillaCommandWrapper.dispatchVanillaCommand(VanillaCommandWrapper.java:109) [minecraft_server.jar:git-Spigot-7d78b81-a6d8fa2]
at org.bukkit.craftbukkit.v1_11_R1.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:38) [minecraft_server.jar:git-Spigot-7d78b81-a6d8fa2]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [minecraft_server.jar:git-Spigot-7d78b81-a6d8fa2]
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649) [minecraft_server.jar:git-Spigot-7d78b81-a6d8fa2]
at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344) [minecraft_server.jar:git-Spigot-7d78b81-a6d8fa2]
at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179) [minecraft_server.jar:git-Spigot-7d78b81-a6d8fa2]
at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [minecraft_server.jar:git-Spigot-7d78b81-a6d8fa2]
at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [minecraft_server.jar:git-Spigot-7d78b81-a6d8fa2]
at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Spigot-7d78b81-a6d8fa2]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [minecraft_server.jar:git-Spigot-7d78b81-a6d8fa2]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [minecraft_server.jar:git-Spigot-7d78b81-a6d8fa2]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [minecraft_server.jar:git-Spigot-7d78b81-a6d8fa2]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [minecraft_server.jar:git-Spigot-7d78b81-a6d8fa2]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [minecraft_server.jar:git-Spigot-7d78b81-a6d8fa2]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
at de.germanspacebuild.plugins.fasttravel.util.FastTravelUtil.isMoveWand(FastTravelUtil.java:55) ~[?:?]
at de.germanspacebuild.plugins.fasttravel.Listener.FTPlayerListener.onPlayerItemDropEvent(FTPlayerListener.java:131) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[minecraft_server.jar:git-Spigot-7d78b81-a6d8fa2]
... 23 more
```

**Comment by NigelThorne** [comment]
see pull request
